### ISSUE TITLE
Updates to OER export 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw_oer_export#100]
### Description/Context

We got come feedback on the export format and there a few areas for improvement: 

- [x] CR_COU_TITLE should use the abbreviated version. Currently, all our courses are `cc-by-nc-sa`
- [x] CR_PROVIDER can be omitted. It's provided by the input workflow. 
- [x] CR_PROVIDER_SET should be formatted "MIT:MIT OpenCourseWare" 
- [x] Replace "Women's Studies" everywhere with "Gender and Sexuality Studies," in CR_SUBJECT and CR_KEYWORDS
- [x] CR_SUBJECT: map OCW's "Physical Education and Recreation" to "Physical Education" in "Education"
- [x] CR_SUBLEVEL "Career/Technical Education" should be replaced with "Career / Technical" (remove "Education")

**Comment by pmusser** [comment]
Thanks Peter! If any questions about these, I'm happy to answer.

**Comment by ibrahimjaved12** [comment]
@pdpinch,

I noticed the sentence in the feedback was incomplete:
`CR_SUBJECT: map OCW's "Physical Education and Recreation" to "Physical Education" in`

Currently, the entry is:
```
OCW Topic,OER Subject,OER Keyword
Physical Education and Recreation,"Health, Medicine and Nursing",Physical Education and Recreation
```

Should this be updated to:
`Physical Education and Recreation,"Health, Medicine and Nursing",Physical Education
`
?

Here’s the PR for reference: https://github.com/mitodl/ocw_oer_export/pull/114

**Comment by pdpinch** [comment]
> Currently, the entry is:

> OCW Topic,OER Subject,OER Keyword
> Physical Education and Recreation,"Health, Medicine and Nursing",Physical Education and Recreation

> Should this be updated to:
> Physical Education and Recreation,"Health, Medicine and Nursing",Physical Education 

I think the more important change is to the OER Subject. It should be "Physical Education" 

I dropped a comment on the PR to be specific: https://github.com/mitodl/ocw_oer_export/pull/114/files#r1819062652

**Comment by ibrahimjaved12** [comment]
Closing this, all of the things mentioned in the ticket were completed in the PRs linked.
